name: main
on:
  push:
jobs:
  deploy-stg:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - run: |
          echo ${{ secrets.MY_SECRET }}
          echo ${{ env.MY_ENV }}
  deploy-prod:
    needs: deploy-stg
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: |
          echo ${{ secrets.MY_SECRET }}
          echo ${{ env.MY_ENV }}
  deploy-stg-2:
    runs-on: ubuntu-latest
    needs: deploy-stg
    environment: stg
    steps:
      - run: |
          echo ${{ secrets.MY_SECRET }}
          echo ${{ env.MY_ENV }}
